package com.example.socialntw.common.constant;

public class MessageConstant {
    public static final String EMAIL_PASSWORD_INVALID = "Invalid email or password";
    public static final String EMAIL_INVALID = "Invalid email";
    public static final String NAME_INVALID = "Invalid full name";
    public static final String ID_INVALID = "Invalid ID";
    public static final String FIELD_INVALID = "Field cannot be blank";
    public static final String REFRESH_TOKEN_NOT_FOUND = "Refresh token not found in Authorization header";
    public static final String TOKEN_REFRESHED_SUCCESSFULL = "Refresh access token successfully";
    public static final String NOT_FOUND = "item not found";
    public static final String INVALID_REFRESH_TOKEN = "Refresh token is not valid";
    public static final String INVALID_ACCESS_TOKEN = "Access token is not valid";
    public static final String FILE_CREATED_SUCCESS = "Item created successfully";
    public static final String FILE_DELETED_FAILED = "Error occurred while deleting file: ";
    public static final String FILES_DELETED_FAILED = "Failed to delete file from Cloudinary: ";
    public static final String CANNOT_NEGATIVE = "Field can't be negative";
    public static final String USER_EXISTED = "user existed";
    public static final String USER_TYPE_INVALID = "User can only be STUDENT or INSTRUCTOR";
    public static final String COURSE_NOT_FOUND = "Course not found";
    public static final String USERTYPE_INVALID = "Invalid user type";
    public static final String USER_BLOCKED = "user blocked";
    public static final String PASSWORD_DONT_MATCH = "password must match with confirm password";
    public static final String LOGOUT_SUCCESS = "logout success";
    public static final String TOKEN_NOT_FOUND = "refresh token has been deleted";
    public static final String NEW_PASSWORD_CANNOT_BE_OLD_PASSWORD = "New password cannot be old password";
    public static final String WRONG_OlD_PASSWORD = "Old password doesn't match";
    public static final String SUBJECT_ALREADY_ADDED_TO_COURSE = "subject already added to this course";
    public static final String SUBJECT_ALREADY_REMOVED_FROM_COURSE = "subject already removed from this course";
    public static final String SUBJECT_ALREADY_EXIT = "Subject already exits";
    public static final String COURSE_EXIST = "you have already make this course";
    public static final String PHONE_INVALID = "invalid phone number";
    public static final String USER_NOT_FOUND = "User not found";
    public static final String CART_NOT_FOUND = "Cart not found";
    public static final String CART_ALREADY_EXIST = "Cart already exit for this user";
    public static final String COURSE_EXIST_CART = "Course already exist in cart ";
    public static final String CART_ITEM_NOT_FOUND = "Cart item not found";
    public static final String ALREADY_BOUGHT = "User already bought this course";
    public static final String TRANSACTION_FAILED = "Transaction Failed";
    public static final String MATERIAL_NOT_FOUND = "material not found";
    public static final String ALREADY_UNAPPROVED = "course is unapproved";
    public static final String FILE_NOT_FOUND = "file not found";
    public static final String INVALID_FILE_TYPE = "Invalid file type. Only PDF, image, and MP4 files are allowed.";
    public static final String SUBJECT_NOT_FOUND = "Subject not found";
}
